# Generated by Django 5.0.2 on 2024-04-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_membershiperequesite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiperequesite',
            name='status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject'), ('Pending', 'Pending')], default='Pending', max_length=64),
        ),
    ]
