# Generated by Django 5.0.2 on 2024-04-28 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0004_discussion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('agenda', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.DateTimeField()),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50)),
                ('start_url', models.URLField(blank=True, null=True)),
                ('join_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
