# Generated by Django 5.0.4 on 2024-04-22 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_sets', '0002_remove_reviewset_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
                ('review_sets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_sets.reviewset')),
            ],
        ),
    ]
