# Generated by Django 5.0.4 on 2024-04-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('review_sets', '0004_remove_flashcard_review_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewset',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.studygroup'),
            preserve_default=False,
        ),
    ]
