# Generated by Django 5.0.4 on 2024-04-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_sets', '0005_reviewset_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewset',
            name='group',
        ),
    ]
