# Generated by Django 5.0.4 on 2024-04-25 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_sets', '0006_remove_reviewset_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='review_sets',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='review_sets.reviewset'),
            preserve_default=False,
        ),
    ]
