# Generated by Django 5.0.4 on 2024-04-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_sets', '0007_flashcard_review_sets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='review_sets',
            new_name='review_set',
        ),
    ]
