# Generated by Django 5.0.2 on 2024-04-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('review_sets', '0008_rename_review_sets_flashcard_review_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewset',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.studygroup'),
            preserve_default=False,
        ),
    ]
